# Generated by Django 5.1.4 on 2024-12-28 10:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Текст новости:'),
        ),
    ]
